Change userspace tools for DOCA mellanox to 3.2LTS
-commit is changing mlnx-tools version to 3.2LTS
-userspace tools : mstflint and rdma-core from master are moved
from kernel repo to integ repo (debian snapshot)
to maintain compatibility for kernel 6.18.y

Test Plan:
Pass: downloader
Pass: build drivers
Pass: build image
Pass: boot
Pass: check driver versions

Story: 2011767
Task: 55177

Depends-On: https://review.opendev.org/c/starlingx/tools/+/1000420

Change-Id: I81ab09403d464617f8006b9a06393aa70777658f
Signed-off-by: Iulian Mocanu <iulian.mocanu@windriver.com>

diff --git a/userspace/mellanox/mlnx-tools/debian/trixie/dl_hook b/userspace/mellanox/mlnx-tools/debian/trixie/dl_hook
--- a/userspace/mellanox/mlnx-tools/debian/trixie/dl_hook
+++ b/userspace/mellanox/mlnx-tools/debian/trixie/dl_hook
@@ -1,27 +1,58 @@
 #!/bin/bash
+#
+# Copyright (c) 2026 Wind River Systems, Inc.
+#
+# Licensed to the Apache Software Foundation (ASF) under one
+# or more contributor license agreements. The ASF licenses this
+# file to you under the Apache License, Version 2.0 (the
+# "License"); you may not use this file except in compliance
+# with the License.  You may obtain a copy of the License at
+#
+#  http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing,
+# software distributed under the License is distributed on an
+# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+# KIND, either express or implied.  See the License for the
+# specific language governing permissions and limitations
+# under the License.
+#
 
-DOCA_PKG=doca-mlnx-ofed-3.3.0.tgz
+# The only parameter is the name of the new directory that will contain
+# the extracted source code. Be aware that this new directory will be
+# created in the same directory as where this script is located when
+# building.
+# Tools needed: mkdir, rm, tar
 
-tar zxvf ${DOCA_PKG}
-if [ $? -ne 0 ]
-then
-    echo "tar failed: DOCA_PKG source!"
+set -e
+
+DOCA_PKG=doca-mlnx-tools.tgz
+
+# Derive the version from local_debian/meta_data.yaml (debver)
+META_DATA="$(cd "$(dirname "$0")" && pwd)"
+YAML="$META_DATA/local_debian/meta_data.yaml"
+
+DOCA_VERSION="$(awk -F': *' '/^debver:/ {gsub(/["'\'']/,"",$2); print $2; exit}' "$YAML")"
+if [ -z "$DOCA_VERSION" ]; then
+    echo "failed to read debver from ${YAML}!"
     exit 1
 fi
 
-cd MLNX_OFED_SRC-26.01-1.0.0.0/SOURCES
+mkdir MLNX_OFED_SRC
+tar zxvf "${DOCA_PKG}" -C MLNX_OFED_SRC
 if [ $? -ne 0 ]
 then
-    echo "SOURCES failed: DOCA_PKG source!"
+    echo "tar failed: ${DOCA_PKG} !"
     exit 1
 fi
 
-cp mlnx-tools_2601.0.2.orig.tar.gz ../../
-tar zxvf mlnx-tools_2601.0.2.orig.tar.gz
+mkdir MLNX_OFED_ORIG
+cp MLNX_OFED_SRC/*/SOURCES/mlnx-tools_*.orig.tar.gz .
+tar zxvf mlnx-tools_*.orig.tar.gz -C MLNX_OFED_ORIG
 if [ $? -ne 0 ]
 then
-    echo "tar failed: DOCA_PKG source!"
+    echo "tar failed: MLNX_OFED_SRC!"
     exit 1
 fi
 
-cp -r mlnx-tools-2601.0.2 ../../doca-mlnx-tools-3.3.0
+mv MLNX_OFED_ORIG/mlnx-tools* "doca-mlnx-tools-${DOCA_VERSION}"
